' '***********************
'  [#0] MAIN ENTRY POINT
' '***********************

sub init()
    initVariables()
    initStyles()
end sub

' '***********************
' [#1]: VARIABLES
' '***********************

sub initVariables()
    m.loadingIndicator = m.top.findNode("loadingIndicator")
    m.backGroundSpinner = m.top.findNode("backGroundSpinner")
end sub

' '***********************
' [#3]: SETUPS
' '***********************

sub initStyles()
    m.loadingIndicator.poster.uri = "pkg:/images/spinner.png"
    m.backGroundSpinner.uri= "pkg:/images/spinnerBackground.png"
end sub

' '***********************
' [#2]: OBSERVERS
' '***********************

' '***********************
' [#4]: EVENTS
' '***********************

sub onLoadCompleted(event as object)
    isLoadCompleted = event.getData()

    if isLoadCompleted = true
        m.loadingIndicator.visible = false
        m.backGroundSpinner.visible = false
    end if
end sub



