import "pkg:/source/FocusHandler.bs"

sub init()
    bindVariables()
    bindStyles()
    bindObservers()
end sub

sub bindObservers()
    m.top.observeField("focusedChild", "onFocusChildChange")
end sub

sub bindVariables()
    m.title = m.top.findNode("title")
    m.tyC = m.top.findNode("tyC")
    m.signUpButton = m.top.findNode("signUpButton")
    m.skipButton = m.top.findNode("skipButton")
end sub

sub bindStyles()
    m.title.text = SignUpScreen.TITTLE
    m.tyC.text = SignUpScreen.TYC

    applyFocusTo(m.signUpButton, m.signUpButton.id)
    stopLoad()
end sub

sub stopLoad()
    m.top.loadCompleted = true
end sub

sub onFocusChildChange()
    getAllFocusedNodes()
end sub

function onKeyEvent(key as String, press as Boolean) as Boolean
	handled = false
	if press
		if key = "OK"
			if m.signUpButton.isInFocusChain()
				? "FOCO ENCONTRADO"
			end if
		end if
		handled = true
	end if
	return handled
end function