' '***********************
' IMPORTS
' '***********************

import "pkg:/source/FocusHandler.bs"

' '***********************
'  [#0] MAIN ENTRY POINT
' '***********************

sub init()
    initVariables()
    initStyles()
    initObservers()
    ' createUserContentTask()
end sub

' '***********************
' [#1]: VARIABLES
' '***********************

sub initVariables()
    m.homeHeaderText = m.top.findNode("homeHeaderText")
    m.watchNowButton = m.top.findNode("watchNowButton")
end sub

' '***********************
' [#2]: OBSERVERS
' '***********************

sub initObservers()
    m.top.observeField("focusedChild", "onFocusedChildChange")
end sub

' '***********************
' [#4]: EVENTS
' '***********************

sub stopLoad()
    m.top.loadCompleted = true
end sub

sub onFocusedChildChange(event as object)
    if m.top.hasFocus() then m.watchNowButton.setFocus(true)
end sub

' '***********************
' [#5]: STYLES
' '***********************

sub initStyles()
    m.homeHeaderText.text       = HomeScreenCopies.HEADER_TEXT
    m.watchNowButton.textButton = HomeScreenCopies.WATCH_NOW

    stopLoad()
end sub

' sub createUserContentTask()
'     m.userContentTask = CreateObject("roSGNode", "usersContentTask")
'     m.userContentTask.url = "https://api-nba-v1.p.rapidapi.com/teams"
'     m.userContentTask.observeField("output", "onOutputChanged")
'     m.userContentTask.control = "RUN"
' end sub

' sub onOutputChanged()
'     m.teamsList = m.top.findNode("teamsList")
' 	m.teamsList.content = m.userContentTask.output
'     applyFocusTo(m.teamsList, m.teamsList.id)
'     m.userContentTask.unObserveField("output")
'     m.userContentTask.control = "stop"
'     m.userContentTask = invalid
'   end if
' end sub

function onKeyEvent(key as String, press as Boolean) as Boolean
	handled = false

	if press
		if key = "OK"
			if m.watchNowButton.isInFocusChain()
				m.watchNowButton.isFocused = true
			end if
        else if key = "down"
            if m.watchNowButton.isInFocusChain()
                m.watchNowButton.isFocused = false
			end if
        else if key = "up"
            if m.top.isInFocusChain()
                m.watchNowButton.setFocus(true)
                m.watchNowButton.isFocused = true
			end if
		end if
		handled = true
	end if
	return handled
end function
