import "pkg:/source/FocusHandler.bs"
import "pkg:/source/EnumsContainer.bs"

sub init()
    setMainViewsMap()
    bindComponents()
end sub

sub bindComponents()
    m.sideBar = m.top.findNode("sideBar")
end sub

sub setMainViewsMap()
    m.viewsMap = {}

    m.viewsMap[ScreenNames.HOME] = ScreenNames.HOME
end sub

sub onViewDataChange()
end sub

sub onViewIdChange(event as object)
    screenId = event.getData()
	screen = m.top.createChild(screenId)
    screen.id = screenId

    applyFocusTo(screen, screen.id)

	m.top.insertChild(screen, 1)

    if m.viewsMap[screenId] <> invalid then m.sideBar.visible = true

    if screen.loadCompleted = true then m.top.loadCompleted = true
end sub

sub navigateTo(location as string, params as object, appendToStack as boolean, saveInCache as boolean)

	screen = m.top.createChild(location)
    screen.id = location

    applyFocusTo(screen, screen.id)

	m.top.insertChild(screen, 1)

    if m.viewsMap[screenId] <> invalid then m.sideBar.visible = true

    if screen.loadCompleted = true then m.top.loadCompleted = true

end sub