enum SignUpScreen
    TITTLE = "CREATE YOUR ACCOUNT AND ENJOY OUR CONTENT"
    TYC = "This channel just have academic porpuses and is non profit app"
end enum

enum HomeScreenCopies
    SUBSCRIBE_BUTTON = "SUBSCRIBE"
    SUBSCRIPTION_LABEL = "Join to NBA channel and watch all exclusive content"
    WATCH_NOW= "WATCH NOW"
end enum

enum ScreenNames
    HOME = "HomeScreen"
    SIGNUP = "SignUpScreen"
end enum


