import "pkg:/source/ValidationUtils.bs"

sub applyFocusTo(node as object, id as string, parentNode = {} as object)
    removeFocusTo(parentNode, id)

    if (Validate.assocArrayNotEmpty(node) or Validate.isSGNode(node)) AND Validate.stringNotEmpty(id) then node.setFocus(true)
    print "****** Applied focus to : "; id; " ******"

    saveNewEntryToFocusRegistry(id)
end sub

sub removeFocusTo(node as object, id as string)
    if (Validate.assocArrayNotEmpty(node) or Validate.isSGNode(node)) AND Validate.stringNotEmpty(id) then node.setFocus(false)
    print "****** Removed focus to : "; id; " ******"
end sub

function getLastFocusedNode()
    return m.global.focusRegistry.count() > 0 ? m.global.focusRegistry.Peek() : m.global.focusRegistry[0]
end function

function getAllFocusedNodes()
    print "****** Total focused nodes : "; m.global.focusRegistry; " ******"
end function

sub saveNewEntryToFocusRegistry(id as string)
    focusHistoricalRecord = m.global.focusRegistry
    focusHistoricalRecord.push(id)

    m.global.focusRegistry = focusHistoricalRecord
end sub